version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_devfeed
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_cmVsYXhpbmctY29sdC01Ni5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_Hj5DCOL1f8J6Z38W19YHcIBf2ubYA19soZFYs2ppov
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=/
      - NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=/
    volumes:
      - sqlite-data:/app/prisma
    restart: unless-stopped

volumes:
  sqlite-data:
